dependencies:
    - pip
    - python=3.5
    - numpy=1.11
    - scipy=1.1.0
    - matplotlib=3.0.0
    - corner=2.0.1
    - ipywidgets=7.5.1
    - ipython=7.0.1
    - python-dateutil=2.7.5
    - python-editor=1.0.3
    - python-oauth2=1.1.0
    - widgetsnbextension=3.5.1
    - pip:
        - git+https://github.com/jan-rybizki/Chempy.git@v0.1
