dependencies:
    - python=3.5
    - alembic
    - backcall=0.1.0
    - bleach=3.0.2
    - certifi=2018.8.24
    - chardet=3.0.4
    - corner=2.0.1
    - cycler=0.10.0
    - decorator=4.3.0
    - defusedxml=0.5.0
    - entrypoints=0.2.3
    - idna=2.7
    - ipykernel=5.1.0
    - ipython=7.0.1
    - ipywidgets=7.5.1
    - jedi=0.12.1
    - Jinja2=2.10
    - jsonschema=2.6.0
    - kiwisolver=1.0.1
    - Mako=1.0.7
    - MarkupSafe=1.0
    - matplotlib=3.0.0
    - mistune=0.8.3
    - nbconvert=5.4.0
    - nbformat=4.4.0
    - notebook=5.7.8
    - numpy=1.11.3
    - pamela=0.3.0
    - pandocfilters=1.4.2
    - parso=0.3.1
    - pexpect=4.6.0
    - pickleshare=0.7.5
    - pip
    - ptyprocess=0.6.0
    - Pygments=2.2.0
    - pyparsing=2.4.7
    - python-dateutil=2.7.5
    - python-editor=1.0.3
    - python-oauth2=1.1.0
    - pytz=2022.1
    - pyzmq=17.1.2
    - requests=2.20.1
    - scipy=1.1.0
    - Send2Trash=1.5.0
    - setuptools=40.4.3
    - simplegeneric=0.8.1
    - six=1.11.0
    - SQLAlchemy=1.2.14
    - terminado=0.8.1
    - testpath=0.3.1
    - tornado=5.1.1
    - traitlets=4.3.2
    - urllib3=1.24.1
    - wcwidth=0.1.7
    - webencodings=0.5.1
    - wheel=0.32.0
    - widgetsnbextension=3.5.1
    - pip:
        - git+https://github.com/jan-rybizki/Chempy.git@v0.1
