dependencies:
    - python=3.5
    - pip
    - nbclassic
    - pip:
        - datetime
    - numpy=1.11
    - scipy
    - matplotlib
    - corner
    - ipywidgets
    - pip:
        - git+https://github.com/jan-rybizki/Chempy.git@v0.1
