dependencies:
    - python=3.5
    - numpy=1.11
    - scipy=1.1
    - matplotlib=3.0
    - corner=2.0
    - ipywidgets=7.5
    - widgetsnbextension=4.0
    - pip:
        - git+https://github.com/jan-rybizki/Chempy.git@v0.1
