dependencies:
    - python=3.10
    - pip
    - pip:
        - git+https://github.com/jan-rybizki/Chempy.git@v0.1
    - numpy
    - scipy
    - matplotlib
    - corner
    - ipywidgets
    - widgetsnbextension

