dependencies:
    - python=3.7
    - pip
    - numpy=1.11
    - scipy
    - matplotlib=3
    - corner
    - ipywidgets=8.1.3
    - widgetsnbextension
    - pip:
        - git+https://github.com/jan-rybizki/Chempy.git@v0.1
